# ─────────────────────────────────────
# 3. GitHub Profile Trophy
# ─────────────────────────────────────
- name: Generate GitHub Trophy
  uses: Erik-Donath/github-profile-trophy@feature/generate-svg
  with:
    username: IMALIMRANS
    output_path: github-trophy.svg
    token: ${{ secrets.GITHUB_TOKEN }}
